image: registry.gitlab.com/pcengines/apu2-documentation:latest

services:
  - docker:dind
  
variables:
  RELEASE_DIR: ${CI_PROJECT_DIR}/apu2_fw_rel

stages:
  - check_dependencies
  - build_crosscompiler
  - build_rom
  - test_rom
  - sign_rom
  - publish_rom

check_dependencies:
  stage: check_dependencies
  script:
    - git ls-remote https://github.com/pcengines/release_manifests.git | grep ${CI_COMMIT_REF_NAME}
  only:
    - tags
    
build_crosscompiler:
  stage: build_crosscompiler
  tags: 
    - docker
  script:
    - test -e ${CI_PROJECT_DIR}/apu2_fw_rel/apu2/coreboot/util/crossgcc/xgcc || { make crossgcc-i386 CPUS=$(nproc) &&  mkdir -p ${CI_PROJECT_DIR}/apu2_fw_rel/apu2/coreboot/util/crossgcc/ && mv -f ${CI_PROJECT_DIR}/util/crossgcc/xgcc ${CI_PROJECT_DIR}/apu2_fw_rel/apu2/coreboot/util/crossgcc/ ; }
  cache:
    key: apu
    paths:
      - ${CI_PROJECT_DIR}/apu2_fw_rel/apu2/coreboot/util/crossgcc/xgcc
  only:
    - tags
    - web    
      
.build_rom_apu: &build_rom_apu
  variables:
    PLATFORM: apux
    MANIFEST_FALLBACK_BRANCH: coreboot-xxxx
  stage: build_rom
  tags: 
    - docker
  dependencies:
    - build_crosscompiler
  script:
    - mkdir -p apu2_fw_rel && cd apu2_fw_rel
    - if [ -n "$CI_COMMIT_TAG" ]; then REPO_REVISION="refs/tags/$CI_COMMIT_REF_NAME"; else REPO_REVISION="$CI_COMMIT_REF_NAME"; fi
    - git ls-remote https://github.com/pcengines/coreboot.git | grep ${REPO_REVISION} || REPO_REVISION="$MANIFEST_FALLBACK_BRANCH"
    - repo init -u https://github.com/pcengines/release_manifests.git -b ${REPO_REVISION}
    - repo sync --force-sync
    - cp ${CI_PROJECT_DIR}/configs/pcengines_${PLATFORM}.config ${CI_PROJECT_DIR}/apu2_fw_rel/apu2/coreboot/.config
    - ${RELEASE_DIR}/apu2/apu2-documentation/scripts/build_release_img.sh build-ml
  cache:
    policy: pull
    key: apu
    paths:
      - ${RELEASE_DIR}/apu2/coreboot/util/crossgcc/xgcc
  artifacts:
    name: ${PLATFORM}
    paths:
      - ${RELEASE_DIR}/${PLATFORM}_*
  only:
    - tags
    - web     
      
.test_rom: &test_rom
  variables:
    PLATFORM: 
  stage: test_rom
  tags:
    - docker
  script:
    - ls -la ${RELEASE_DIR}/${PLATFORM}_*.rom
  only:
    - tags
    - web

.sign_rom: &sign_rom
  variables:
    PLATFORM: 
  stage: sign_rom
  tags:
    - docker
  script:
    - for rom in ${RELEASE_DIR}/${PLATFORM}_*.rom; do touch ${rom}_dummy_signature; done
    - ls -la ${RELEASE_DIR}/${PLATFORM}_*.rom
  artifacts:
    name: ${PLATFORM}
    paths:
      - ${RELEASE_DIR}/${PLATFORM}_* 
  only:
    - tags

.publish_rom: &publish_rom
  variables:
    PLATFORM: 
  stage: publish_rom
  tags:
    - docker
  script:
    - curl -u ${UPLOADER_USERNAME}:${UPLOADER_PASSWORD} -X MKCOL "${UPLOADER_URL}/${PLATFORM}/"; curl -u ${UPLOADER_USERNAME}:${UPLOADER_PASSWORD} -X MKCOL "${UPLOADER_URL}/${PLATFORM}/releases/"
    - for file in ${RELEASE_DIR}/${PLATFORM}_*.tar.gz; do curl --fail -u ${UPLOADER_USERNAME}:${UPLOADER_PASSWORD} -T ${file} "${UPLOADER_URL}/${PLATFORM}/releases/"; done
  only:
    - tags
    
build:apu2:
  <<: *build_rom_apu
  variables:
    PLATFORM: apu2
    MANIFEST_FALLBACK_BRANCH: coreboot-4.6.x

.test:apu2:
  <<: *test_rom
  variables:
    PLATFORM: apu2
    
.sign:apu2:
  <<: *sign_rom
  variables:
    PLATFORM: apu2
    
publish:apu2:
  <<: *publish_rom
  variables:
    PLATFORM: apu2    
    
    
build:apu3:
  <<: *build_rom_apu
  variables:
    PLATFORM: apu3
    MANIFEST_FALLBACK_BRANCH: coreboot-4.6.x

.test:apu3:
  <<: *test_rom
  variables:
    PLATFORM: apu3
    
.sign:apu3:
  <<: *sign_rom
  variables:
    PLATFORM: apu3
    
publish:apu3:
  <<: *publish_rom
  variables:
    PLATFORM: apu3

   
build:apu4:
  <<: *build_rom_apu
  variables:
    PLATFORM: apu4
    MANIFEST_FALLBACK_BRANCH: coreboot-4.6.x

.test:apu4:
  <<: *test_rom
  variables:
    PLATFORM: apu4
    
.sign:apu4:
  <<: *sign_rom
  variables:
    PLATFORM: apu4
    
publish:apu4:
  <<: *publish_rom
  variables:
    PLATFORM: apu4 

    
build:apu5:
  <<: *build_rom_apu
  variables:
    PLATFORM: apu5
    MANIFEST_FALLBACK_BRANCH: coreboot-4.6.x

.test:apu5:
  <<: *test_rom
  variables:
    PLATFORM: apu5
    
.sign:apu5:
  <<: *sign_rom
  variables:
    PLATFORM: apu5
    
publish:apu5:
  <<: *publish_rom
  variables:
    PLATFORM: apu5    
