baseurl = "https://www.coreboot.org/Documentation/"
languageCode = "en-us"
title = "coreboot documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
  provider = "Coreboot"
  repo_url = "https://review.coreboot.org/cgit/coreboot.git"
  logo = "images/coreboot.svg"
  favicon = "images/favicon.png"
  copyright = "corebootâ„¢ contributors, licensed under the terms described in https://creativecommons.org/licenses/by/4.0/"
  custom_css = [
    "css/coreboot.css"
  ]

[social]
	twitter= "coreboot_org"
	github = "coreboot/coreboot"

[params.palette]
	primary = "blue"
	accent  = "blue-grey"

[params.font]
	text = "Open Sans"
	code = "Inconsolata"

[[menu.main]]
        name   = "Gerrit guidelines"
        url    = "gerrit_guidelines/"
        weight = 10

[[menu.main]]
        name   = "On timestamps"
        url    = "timestamp/"
        weight = 20

[[menu.main]]
        name   = "Intel documentation"
        url    = "intel/index.html"
        weight = 30

[[menu.main]]
        name   = "AMD S3"
        url    = "AMD-S3.txt"
        weight = 40
