name: Sync Fork

on:
  schedule:
    - cron: '0 */4 * * *' # every four hours
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_REVIEW_TOKEN }}
          owner: coreboot
          base: main
          head: main
          merge_method: merge
          auto_approve: true
